### ISSUE TITLE
Tower Shard appears in other solar systems sometimes

### ISSUE THREAD

**Issue by MegaPiggy** [xen-42/outer-wilds-new-horizons#140]
### What Happened?

The tower shard will occasionally appear with its mesh and signal but no collisions. 

Here is one near Earth's orbit. 
![image](https://user-images.githubusercontent.com/34462599/169200150-4a3567e3-56d1-40ca-906f-b6b7b5b7a7fc.png)

Here is one **EXTREMELY** far from the solar system. I think it was far away because I left the game running over night.
![image](https://user-images.githubusercontent.com/34462599/169200305-b983c4ab-2d96-454a-85d2-4a1a5502ca26.png)

### What was supposed to happen?

It is not supposed to exist.

### Platform

Epic Games

### Mods

```Markdown
Real Solar System
PacificEngine's Common Resources
Cheats Mod
Unity Explorer
Run In Background
```

**Comment by xen-42** [comment]
Is the tower shard hardcoded to detatch from BH at a certain time in the loop? If so might be that which causes it. If this happens again can you grab the name of the GameObject that's appearing here and then we can just add that to the `GetChildren` method in `AstroObjectLocator` so that it knows to delete it.
